# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install on ${{ matrix.node-version }}
        run: npm install -D
      - name: Normal Build ${{ matrix.node-version }}
        run: npm run build
        if: ${{ matrix.node-version != '18.x' }}
      - name: Normal Build v18+
        run: npm run build
        if: ${{ matrix.node-version == '18.x' }}
        env:
          NODE_OPTIONS:  "--openssl-legacy-provider"
      - name: Build for C5 ${{ matrix.node-version }}
        run: npm run build:c5
        if: ${{ matrix.node-version != '18.x' }}
        env:
          CI: true
      - name: Build for C5 v18+
        if: ${{ matrix.node-version == '18.x' }}
        run: npm run build:c5
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
          CI: true